version: "2.1"

services:
  reposerver:
    container_name: aur_reposerver
    image: reposerver:latest
    restart: always
    networks:
      - web
    expose:
      - "8080"
    labels:
      - "traefik.docker.network=web"
      - "traefik.backend=reposerver"
      - "traefik.frontend.rule=Host:aur.layer8.fail"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
    volumes:
       - /data/archlinux-build/published/:/wwwroot:ro
networks:
  web:
    external: true
